"""
Proxy types returned by TextLayer accessor methods.

Each proxy is a lightweight non-owning handle; it must not outlive the parent
TextLayer.  Setters return ``bool`` (True = success).

Bit-depth variants are identical in interface – only the suffix differs
(_8bit, _16bit, _32bit).
"""

from typing import List, Optional
import psapi.enum


# ---------------------------------------------------------------------------
# StyleRunProxy  –  returned by layer.style_run(run_index)
# ---------------------------------------------------------------------------

class StyleRunProxy_8bit:
    """Proxy for a single character-style run (accessed by index)."""

    @property
    def font_size(self) -> Optional[float]: ...
    @property
    def leading(self) -> Optional[float]: ...
    @property
    def auto_leading(self) -> Optional[bool]: ...
    @property
    def kerning(self) -> Optional[int]: ...
    @property
    def fill_color(self) -> Optional[List[float]]: ...
    @property
    def stroke_color(self) -> Optional[List[float]]: ...
    @property
    def font(self) -> Optional[int]: ...
    @property
    def faux_bold(self) -> Optional[bool]: ...
    @property
    def faux_italic(self) -> Optional[bool]: ...
    @property
    def horizontal_scale(self) -> Optional[float]: ...
    @property
    def vertical_scale(self) -> Optional[float]: ...
    @property
    def tracking(self) -> Optional[int]: ...
    @property
    def auto_kerning(self) -> Optional[bool]: ...
    @property
    def baseline_shift(self) -> Optional[float]: ...
    @property
    def font_caps(self) -> Optional[psapi.enum.FontCaps]: ...
    @property
    def font_baseline(self) -> Optional[psapi.enum.FontBaseline]: ...
    @property
    def no_break(self) -> Optional[bool]: ...
    @property
    def language(self) -> Optional[int]: ...
    @property
    def character_direction(self) -> Optional[psapi.enum.CharacterDirection]: ...
    @property
    def baseline_direction(self) -> Optional[psapi.enum.BaselineDirection]: ...
    @property
    def tsume(self) -> Optional[float]: ...
    @property
    def kashida(self) -> Optional[int]: ...
    @property
    def diacritic_pos(self) -> Optional[psapi.enum.DiacriticPosition]: ...
    @property
    def ligatures(self) -> Optional[bool]: ...
    @property
    def dligatures(self) -> Optional[bool]: ...
    @property
    def underline(self) -> Optional[bool]: ...
    @property
    def strikethrough(self) -> Optional[bool]: ...
    @property
    def stroke_flag(self) -> Optional[bool]: ...
    @property
    def fill_flag(self) -> Optional[bool]: ...
    @property
    def fill_first(self) -> Optional[bool]: ...
    @property
    def outline_width(self) -> Optional[float]: ...

    def set_font_size(self, font_size: float) -> bool: ...
    def set_leading(self, leading: float) -> bool: ...
    def set_auto_leading(self, auto_leading: bool) -> bool: ...
    def set_kerning(self, kerning: int) -> bool: ...
    def set_fill_color(self, values: List[float]) -> bool: ...
    def set_stroke_color(self, values: List[float]) -> bool: ...
    def set_font(self, font: int) -> bool: ...
    def set_font_by_name(self, postscript_name: str) -> bool: ...
    def set_faux_bold(self, faux_bold: bool) -> bool: ...
    def set_faux_italic(self, faux_italic: bool) -> bool: ...
    def set_horizontal_scale(self, horizontal_scale: float) -> bool: ...
    def set_vertical_scale(self, vertical_scale: float) -> bool: ...
    def set_tracking(self, tracking: int) -> bool: ...
    def set_auto_kerning(self, auto_kerning: bool) -> bool: ...
    def set_baseline_shift(self, baseline_shift: float) -> bool: ...
    def set_font_caps(self, font_caps: psapi.enum.FontCaps) -> bool: ...
    def set_font_baseline(self, font_baseline: psapi.enum.FontBaseline) -> bool: ...
    def set_no_break(self, no_break: bool) -> bool: ...
    def set_language(self, language: int) -> bool: ...
    def set_character_direction(self, character_direction: psapi.enum.CharacterDirection) -> bool: ...
    def set_baseline_direction(self, baseline_direction: psapi.enum.BaselineDirection) -> bool: ...
    def set_tsume(self, tsume: float) -> bool: ...
    def set_kashida(self, kashida: int) -> bool: ...
    def set_diacritic_pos(self, diacritic_pos: psapi.enum.DiacriticPosition) -> bool: ...
    def set_ligatures(self, ligatures: bool) -> bool: ...
    def set_dligatures(self, dligatures: bool) -> bool: ...
    def set_underline(self, underline: bool) -> bool: ...
    def set_strikethrough(self, strikethrough: bool) -> bool: ...
    def set_stroke_flag(self, stroke_flag: bool) -> bool: ...
    def set_fill_flag(self, fill_flag: bool) -> bool: ...
    def set_fill_first(self, fill_first: bool) -> bool: ...
    def set_outline_width(self, outline_width: float) -> bool: ...


class StyleRunProxy_16bit(StyleRunProxy_8bit): ...
class StyleRunProxy_32bit(StyleRunProxy_8bit): ...


# ---------------------------------------------------------------------------
# StyleNormalProxy  –  returned by layer.style_normal()
# ---------------------------------------------------------------------------

class StyleNormalProxy_8bit:
    """Proxy for the normal (default) character style sheet."""

    @property
    def sheet_index(self) -> Optional[int]: ...
    @property
    def font(self) -> Optional[int]: ...
    @property
    def font_size(self) -> Optional[float]: ...
    @property
    def leading(self) -> Optional[float]: ...
    @property
    def auto_leading(self) -> Optional[bool]: ...
    @property
    def kerning(self) -> Optional[int]: ...
    @property
    def faux_bold(self) -> Optional[bool]: ...
    @property
    def faux_italic(self) -> Optional[bool]: ...
    @property
    def horizontal_scale(self) -> Optional[float]: ...
    @property
    def vertical_scale(self) -> Optional[float]: ...
    @property
    def tracking(self) -> Optional[int]: ...
    @property
    def auto_kerning(self) -> Optional[bool]: ...
    @property
    def baseline_shift(self) -> Optional[float]: ...
    @property
    def font_caps(self) -> Optional[psapi.enum.FontCaps]: ...
    @property
    def font_baseline(self) -> Optional[psapi.enum.FontBaseline]: ...
    @property
    def no_break(self) -> Optional[bool]: ...
    @property
    def language(self) -> Optional[int]: ...
    @property
    def character_direction(self) -> Optional[psapi.enum.CharacterDirection]: ...
    @property
    def baseline_direction(self) -> Optional[psapi.enum.BaselineDirection]: ...
    @property
    def tsume(self) -> Optional[float]: ...
    @property
    def kashida(self) -> Optional[int]: ...
    @property
    def diacritic_pos(self) -> Optional[psapi.enum.DiacriticPosition]: ...
    @property
    def ligatures(self) -> Optional[bool]: ...
    @property
    def dligatures(self) -> Optional[bool]: ...
    @property
    def underline(self) -> Optional[bool]: ...
    @property
    def strikethrough(self) -> Optional[bool]: ...
    @property
    def stroke_flag(self) -> Optional[bool]: ...
    @property
    def fill_flag(self) -> Optional[bool]: ...
    @property
    def fill_first(self) -> Optional[bool]: ...
    @property
    def outline_width(self) -> Optional[float]: ...
    @property
    def fill_color(self) -> Optional[List[float]]: ...
    @property
    def stroke_color(self) -> Optional[List[float]]: ...

    def set_sheet_index(self, sheet_index: int) -> bool: ...
    def set_font(self, font: int) -> bool: ...
    def set_font_by_name(self, postscript_name: str) -> bool: ...
    def set_font_size(self, font_size: float) -> bool: ...
    def set_leading(self, leading: float) -> bool: ...
    def set_auto_leading(self, auto_leading: bool) -> bool: ...
    def set_kerning(self, kerning: int) -> bool: ...
    def set_faux_bold(self, faux_bold: bool) -> bool: ...
    def set_faux_italic(self, faux_italic: bool) -> bool: ...
    def set_horizontal_scale(self, horizontal_scale: float) -> bool: ...
    def set_vertical_scale(self, vertical_scale: float) -> bool: ...
    def set_tracking(self, tracking: int) -> bool: ...
    def set_auto_kerning(self, auto_kerning: bool) -> bool: ...
    def set_baseline_shift(self, baseline_shift: float) -> bool: ...
    def set_font_caps(self, font_caps: psapi.enum.FontCaps) -> bool: ...
    def set_font_baseline(self, font_baseline: psapi.enum.FontBaseline) -> bool: ...
    def set_no_break(self, no_break: bool) -> bool: ...
    def set_language(self, language: int) -> bool: ...
    def set_character_direction(self, character_direction: psapi.enum.CharacterDirection) -> bool: ...
    def set_baseline_direction(self, baseline_direction: psapi.enum.BaselineDirection) -> bool: ...
    def set_tsume(self, tsume: float) -> bool: ...
    def set_kashida(self, kashida: int) -> bool: ...
    def set_diacritic_pos(self, diacritic_pos: psapi.enum.DiacriticPosition) -> bool: ...
    def set_ligatures(self, ligatures: bool) -> bool: ...
    def set_dligatures(self, dligatures: bool) -> bool: ...
    def set_underline(self, underline: bool) -> bool: ...
    def set_strikethrough(self, strikethrough: bool) -> bool: ...
    def set_stroke_flag(self, stroke_flag: bool) -> bool: ...
    def set_fill_flag(self, fill_flag: bool) -> bool: ...
    def set_fill_first(self, fill_first: bool) -> bool: ...
    def set_outline_width(self, outline_width: float) -> bool: ...
    def set_fill_color(self, values: List[float]) -> bool: ...
    def set_stroke_color(self, values: List[float]) -> bool: ...


class StyleNormalProxy_16bit(StyleNormalProxy_8bit): ...
class StyleNormalProxy_32bit(StyleNormalProxy_8bit): ...


# ---------------------------------------------------------------------------
# ParagraphRunProxy  –  returned by layer.paragraph_run(run_index)
# ---------------------------------------------------------------------------

class ParagraphRunProxy_8bit:
    """Proxy for a single paragraph-style run (accessed by index)."""

    @property
    def justification(self) -> Optional[psapi.enum.Justification]: ...
    @property
    def first_line_indent(self) -> Optional[float]: ...
    @property
    def start_indent(self) -> Optional[float]: ...
    @property
    def end_indent(self) -> Optional[float]: ...
    @property
    def space_before(self) -> Optional[float]: ...
    @property
    def space_after(self) -> Optional[float]: ...
    @property
    def auto_hyphenate(self) -> Optional[bool]: ...
    @property
    def hyphenated_word_size(self) -> Optional[int]: ...
    @property
    def pre_hyphen(self) -> Optional[int]: ...
    @property
    def post_hyphen(self) -> Optional[int]: ...
    @property
    def consecutive_hyphens(self) -> Optional[int]: ...
    @property
    def zone(self) -> Optional[float]: ...
    @property
    def word_spacing(self) -> Optional[List[float]]: ...
    @property
    def letter_spacing(self) -> Optional[List[float]]: ...
    @property
    def glyph_spacing(self) -> Optional[List[float]]: ...
    @property
    def auto_leading(self) -> Optional[float]: ...
    @property
    def leading_type(self) -> Optional[psapi.enum.LeadingType]: ...
    @property
    def hanging(self) -> Optional[bool]: ...
    @property
    def burasagari(self) -> Optional[bool]: ...
    @property
    def kinsoku_order(self) -> Optional[psapi.enum.KinsokuOrder]: ...
    @property
    def every_line_composer(self) -> Optional[bool]: ...

    def set_justification(self, justification: psapi.enum.Justification) -> bool: ...
    def set_first_line_indent(self, first_line_indent: float) -> bool: ...
    def set_start_indent(self, start_indent: float) -> bool: ...
    def set_end_indent(self, end_indent: float) -> bool: ...
    def set_space_before(self, space_before: float) -> bool: ...
    def set_space_after(self, space_after: float) -> bool: ...
    def set_auto_hyphenate(self, auto_hyphenate: bool) -> bool: ...
    def set_hyphenated_word_size(self, hyphenated_word_size: int) -> bool: ...
    def set_pre_hyphen(self, pre_hyphen: int) -> bool: ...
    def set_post_hyphen(self, post_hyphen: int) -> bool: ...
    def set_consecutive_hyphens(self, consecutive_hyphens: int) -> bool: ...
    def set_zone(self, zone: float) -> bool: ...
    def set_word_spacing(self, word_spacing: List[float]) -> bool: ...
    def set_letter_spacing(self, letter_spacing: List[float]) -> bool: ...
    def set_glyph_spacing(self, glyph_spacing: List[float]) -> bool: ...
    def set_auto_leading(self, auto_leading: float) -> bool: ...
    def set_leading_type(self, leading_type: psapi.enum.LeadingType) -> bool: ...
    def set_hanging(self, hanging: bool) -> bool: ...
    def set_burasagari(self, burasagari: bool) -> bool: ...
    def set_kinsoku_order(self, kinsoku_order: psapi.enum.KinsokuOrder) -> bool: ...
    def set_every_line_composer(self, every_line_composer: bool) -> bool: ...


class ParagraphRunProxy_16bit(ParagraphRunProxy_8bit): ...
class ParagraphRunProxy_32bit(ParagraphRunProxy_8bit): ...


# ---------------------------------------------------------------------------
# ParagraphNormalProxy  –  returned by layer.paragraph_normal()
# ---------------------------------------------------------------------------

class ParagraphNormalProxy_8bit(ParagraphRunProxy_8bit):
    """Proxy for the normal (default) paragraph style sheet."""

    @property
    def sheet_index(self) -> Optional[int]: ...
    def set_sheet_index(self, sheet_index: int) -> bool: ...


class ParagraphNormalProxy_16bit(ParagraphNormalProxy_8bit): ...
class ParagraphNormalProxy_32bit(ParagraphNormalProxy_8bit): ...


# ---------------------------------------------------------------------------
# FontProxy  –  returned by layer.font(font_index)
# ---------------------------------------------------------------------------

class FontProxy_8bit:
    """Proxy for a single entry in the layer's FontSet."""

    @property
    def postscript_name(self) -> Optional[str]: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def script(self) -> Optional[psapi.enum.FontScript]: ...
    @property
    def type(self) -> Optional[psapi.enum.FontType]: ...
    @property
    def synthetic(self) -> Optional[int]: ...
    @property
    def is_sentinel(self) -> bool: ...

    def set_postscript_name(self, name: str) -> bool: ...


class FontProxy_16bit(FontProxy_8bit): ...
class FontProxy_32bit(FontProxy_8bit): ...


# ---------------------------------------------------------------------------
# FontSetProxy  –  returned by layer.font_set()
# ---------------------------------------------------------------------------

class FontSetProxy_8bit:
    """Proxy for the layer's FontSet as a whole."""

    @property
    def count(self) -> int: ...
    @property
    def used_indices(self) -> List[int]: ...
    @property
    def used_names(self) -> List[str]: ...

    def find_index(self, postscript_name: str) -> int:
        """Return the index of the font with the given PostScript name, or -1."""
        ...

    def add(
        self,
        postscript_name: str,
        font_type: psapi.enum.FontType = ...,
        script: psapi.enum.FontScript = ...,
        synthetic: int = ...,
    ) -> int:
        """Add a font to the FontSet and return its index."""
        ...


class FontSetProxy_16bit(FontSetProxy_8bit): ...
class FontSetProxy_32bit(FontSetProxy_8bit): ...
