from typing import List

import psapi.enum


class CharacterStyleRange_8bit:
    """Proxy for applying character styles to a range of text on a TextLayer_8bit.

    Obtained via ``style_range()``, ``style_text()``, or ``style_all()``.
    All setter methods are chainable and return ``self``.
    """

    def valid(self) -> bool:
        """True if this proxy targets at least one character range."""
        ...

    def range_count(self) -> int:
        """Number of character ranges this proxy covers."""
        ...

    def set_font_size(self, size: float) -> CharacterStyleRange_8bit: ...
    def set_leading(self, value: float) -> CharacterStyleRange_8bit: ...
    def set_auto_leading(self, value: bool) -> CharacterStyleRange_8bit: ...
    def set_kerning(self, value: int) -> CharacterStyleRange_8bit: ...
    def set_bold(self, value: bool) -> CharacterStyleRange_8bit: ...
    def set_italic(self, value: bool) -> CharacterStyleRange_8bit: ...
    def set_underline(self, value: bool) -> CharacterStyleRange_8bit: ...
    def set_strikethrough(self, value: bool) -> CharacterStyleRange_8bit: ...
    def set_fill_color(self, color: List[float]) -> CharacterStyleRange_8bit: ...
    def set_stroke_color(self, color: List[float]) -> CharacterStyleRange_8bit: ...
    def set_stroke_flag(self, value: bool) -> CharacterStyleRange_8bit: ...
    def set_fill_flag(self, value: bool) -> CharacterStyleRange_8bit: ...
    def set_fill_first(self, value: bool) -> CharacterStyleRange_8bit: ...
    def set_outline_width(self, width: float) -> CharacterStyleRange_8bit: ...
    def set_horizontal_scale(self, value: float) -> CharacterStyleRange_8bit: ...
    def set_vertical_scale(self, value: float) -> CharacterStyleRange_8bit: ...
    def set_tracking(self, value: int) -> CharacterStyleRange_8bit: ...
    def set_auto_kerning(self, value: bool) -> CharacterStyleRange_8bit: ...
    def set_baseline_shift(self, value: float) -> CharacterStyleRange_8bit: ...
    def set_font_caps(self, value: psapi.enum.FontCaps) -> CharacterStyleRange_8bit: ...
    def set_font_baseline(self, value: psapi.enum.FontBaseline) -> CharacterStyleRange_8bit: ...
    def set_no_break(self, value: bool) -> CharacterStyleRange_8bit: ...
    def set_language(self, value: int) -> CharacterStyleRange_8bit: ...
    def set_ligatures(self, value: bool) -> CharacterStyleRange_8bit: ...
    def set_dligatures(self, value: bool) -> CharacterStyleRange_8bit: ...
    def set_font(self, postscript_name: str) -> CharacterStyleRange_8bit:
        """Set font by PostScript name. Adds to FontSet if not present."""
        ...
    def set_font_index(self, index: int) -> CharacterStyleRange_8bit:
        """Set font by index into the FontSet."""
        ...


class CharacterStyleRange_16bit:
    """Proxy for applying character styles to a range of text on a TextLayer_16bit."""

    def valid(self) -> bool: ...
    def range_count(self) -> int: ...
    def set_font_size(self, size: float) -> CharacterStyleRange_16bit: ...
    def set_leading(self, value: float) -> CharacterStyleRange_16bit: ...
    def set_auto_leading(self, value: bool) -> CharacterStyleRange_16bit: ...
    def set_kerning(self, value: int) -> CharacterStyleRange_16bit: ...
    def set_bold(self, value: bool) -> CharacterStyleRange_16bit: ...
    def set_italic(self, value: bool) -> CharacterStyleRange_16bit: ...
    def set_underline(self, value: bool) -> CharacterStyleRange_16bit: ...
    def set_strikethrough(self, value: bool) -> CharacterStyleRange_16bit: ...
    def set_fill_color(self, color: List[float]) -> CharacterStyleRange_16bit: ...
    def set_stroke_color(self, color: List[float]) -> CharacterStyleRange_16bit: ...
    def set_stroke_flag(self, value: bool) -> CharacterStyleRange_16bit: ...
    def set_fill_flag(self, value: bool) -> CharacterStyleRange_16bit: ...
    def set_fill_first(self, value: bool) -> CharacterStyleRange_16bit: ...
    def set_outline_width(self, width: float) -> CharacterStyleRange_16bit: ...
    def set_horizontal_scale(self, value: float) -> CharacterStyleRange_16bit: ...
    def set_vertical_scale(self, value: float) -> CharacterStyleRange_16bit: ...
    def set_tracking(self, value: int) -> CharacterStyleRange_16bit: ...
    def set_auto_kerning(self, value: bool) -> CharacterStyleRange_16bit: ...
    def set_baseline_shift(self, value: float) -> CharacterStyleRange_16bit: ...
    def set_font_caps(self, value: psapi.enum.FontCaps) -> CharacterStyleRange_16bit: ...
    def set_font_baseline(self, value: psapi.enum.FontBaseline) -> CharacterStyleRange_16bit: ...
    def set_no_break(self, value: bool) -> CharacterStyleRange_16bit: ...
    def set_language(self, value: int) -> CharacterStyleRange_16bit: ...
    def set_ligatures(self, value: bool) -> CharacterStyleRange_16bit: ...
    def set_dligatures(self, value: bool) -> CharacterStyleRange_16bit: ...
    def set_font(self, postscript_name: str) -> CharacterStyleRange_16bit: ...
    def set_font_index(self, index: int) -> CharacterStyleRange_16bit: ...


class CharacterStyleRange_32bit:
    """Proxy for applying character styles to a range of text on a TextLayer_32bit."""

    def valid(self) -> bool: ...
    def range_count(self) -> int: ...
    def set_font_size(self, size: float) -> CharacterStyleRange_32bit: ...
    def set_leading(self, value: float) -> CharacterStyleRange_32bit: ...
    def set_auto_leading(self, value: bool) -> CharacterStyleRange_32bit: ...
    def set_kerning(self, value: int) -> CharacterStyleRange_32bit: ...
    def set_bold(self, value: bool) -> CharacterStyleRange_32bit: ...
    def set_italic(self, value: bool) -> CharacterStyleRange_32bit: ...
    def set_underline(self, value: bool) -> CharacterStyleRange_32bit: ...
    def set_strikethrough(self, value: bool) -> CharacterStyleRange_32bit: ...
    def set_fill_color(self, color: List[float]) -> CharacterStyleRange_32bit: ...
    def set_stroke_color(self, color: List[float]) -> CharacterStyleRange_32bit: ...
    def set_stroke_flag(self, value: bool) -> CharacterStyleRange_32bit: ...
    def set_fill_flag(self, value: bool) -> CharacterStyleRange_32bit: ...
    def set_fill_first(self, value: bool) -> CharacterStyleRange_32bit: ...
    def set_outline_width(self, width: float) -> CharacterStyleRange_32bit: ...
    def set_horizontal_scale(self, value: float) -> CharacterStyleRange_32bit: ...
    def set_vertical_scale(self, value: float) -> CharacterStyleRange_32bit: ...
    def set_tracking(self, value: int) -> CharacterStyleRange_32bit: ...
    def set_auto_kerning(self, value: bool) -> CharacterStyleRange_32bit: ...
    def set_baseline_shift(self, value: float) -> CharacterStyleRange_32bit: ...
    def set_font_caps(self, value: psapi.enum.FontCaps) -> CharacterStyleRange_32bit: ...
    def set_font_baseline(self, value: psapi.enum.FontBaseline) -> CharacterStyleRange_32bit: ...
    def set_no_break(self, value: bool) -> CharacterStyleRange_32bit: ...
    def set_language(self, value: int) -> CharacterStyleRange_32bit: ...
    def set_ligatures(self, value: bool) -> CharacterStyleRange_32bit: ...
    def set_dligatures(self, value: bool) -> CharacterStyleRange_32bit: ...
    def set_font(self, postscript_name: str) -> CharacterStyleRange_32bit: ...
    def set_font_index(self, index: int) -> CharacterStyleRange_32bit: ...


class ParagraphStyleRange_8bit:
    """Proxy for applying paragraph styles to a range of text on a TextLayer_8bit.

    Obtained via ``paragraph_range()``, ``paragraph_text()``, or ``paragraph_all()``.
    All setter methods are chainable and return ``self``.
    """

    def valid(self) -> bool: ...
    def range_count(self) -> int: ...
    def set_justification(self, value: psapi.enum.Justification) -> ParagraphStyleRange_8bit: ...
    def set_first_line_indent(self, value: float) -> ParagraphStyleRange_8bit: ...
    def set_start_indent(self, value: float) -> ParagraphStyleRange_8bit: ...
    def set_end_indent(self, value: float) -> ParagraphStyleRange_8bit: ...
    def set_space_before(self, value: float) -> ParagraphStyleRange_8bit: ...
    def set_space_after(self, value: float) -> ParagraphStyleRange_8bit: ...
    def set_auto_hyphenate(self, value: bool) -> ParagraphStyleRange_8bit: ...
    def set_hyphenated_word_size(self, value: int) -> ParagraphStyleRange_8bit: ...
    def set_pre_hyphen(self, value: int) -> ParagraphStyleRange_8bit: ...
    def set_post_hyphen(self, value: int) -> ParagraphStyleRange_8bit: ...
    def set_consecutive_hyphens(self, value: int) -> ParagraphStyleRange_8bit: ...
    def set_zone(self, value: float) -> ParagraphStyleRange_8bit: ...
    def set_word_spacing(self, value: List[float]) -> ParagraphStyleRange_8bit: ...
    def set_letter_spacing(self, value: List[float]) -> ParagraphStyleRange_8bit: ...
    def set_glyph_spacing(self, value: List[float]) -> ParagraphStyleRange_8bit: ...
    def set_auto_leading(self, value: float) -> ParagraphStyleRange_8bit: ...
    def set_leading_type(self, value: psapi.enum.LeadingType) -> ParagraphStyleRange_8bit: ...
    def set_hanging(self, value: bool) -> ParagraphStyleRange_8bit: ...
    def set_burasagari(self, value: bool) -> ParagraphStyleRange_8bit: ...
    def set_kinsoku_order(self, value: psapi.enum.KinsokuOrder) -> ParagraphStyleRange_8bit: ...
    def set_every_line_composer(self, value: bool) -> ParagraphStyleRange_8bit: ...


class ParagraphStyleRange_16bit:
    """Proxy for applying paragraph styles to a range of text on a TextLayer_16bit."""

    def valid(self) -> bool: ...
    def range_count(self) -> int: ...
    def set_justification(self, value: psapi.enum.Justification) -> ParagraphStyleRange_16bit: ...
    def set_first_line_indent(self, value: float) -> ParagraphStyleRange_16bit: ...
    def set_start_indent(self, value: float) -> ParagraphStyleRange_16bit: ...
    def set_end_indent(self, value: float) -> ParagraphStyleRange_16bit: ...
    def set_space_before(self, value: float) -> ParagraphStyleRange_16bit: ...
    def set_space_after(self, value: float) -> ParagraphStyleRange_16bit: ...
    def set_auto_hyphenate(self, value: bool) -> ParagraphStyleRange_16bit: ...
    def set_hyphenated_word_size(self, value: int) -> ParagraphStyleRange_16bit: ...
    def set_pre_hyphen(self, value: int) -> ParagraphStyleRange_16bit: ...
    def set_post_hyphen(self, value: int) -> ParagraphStyleRange_16bit: ...
    def set_consecutive_hyphens(self, value: int) -> ParagraphStyleRange_16bit: ...
    def set_zone(self, value: float) -> ParagraphStyleRange_16bit: ...
    def set_word_spacing(self, value: List[float]) -> ParagraphStyleRange_16bit: ...
    def set_letter_spacing(self, value: List[float]) -> ParagraphStyleRange_16bit: ...
    def set_glyph_spacing(self, value: List[float]) -> ParagraphStyleRange_16bit: ...
    def set_auto_leading(self, value: float) -> ParagraphStyleRange_16bit: ...
    def set_leading_type(self, value: psapi.enum.LeadingType) -> ParagraphStyleRange_16bit: ...
    def set_hanging(self, value: bool) -> ParagraphStyleRange_16bit: ...
    def set_burasagari(self, value: bool) -> ParagraphStyleRange_16bit: ...
    def set_kinsoku_order(self, value: psapi.enum.KinsokuOrder) -> ParagraphStyleRange_16bit: ...
    def set_every_line_composer(self, value: bool) -> ParagraphStyleRange_16bit: ...


class ParagraphStyleRange_32bit:
    """Proxy for applying paragraph styles to a range of text on a TextLayer_32bit."""

    def valid(self) -> bool: ...
    def range_count(self) -> int: ...
    def set_justification(self, value: psapi.enum.Justification) -> ParagraphStyleRange_32bit: ...
    def set_first_line_indent(self, value: float) -> ParagraphStyleRange_32bit: ...
    def set_start_indent(self, value: float) -> ParagraphStyleRange_32bit: ...
    def set_end_indent(self, value: float) -> ParagraphStyleRange_32bit: ...
    def set_space_before(self, value: float) -> ParagraphStyleRange_32bit: ...
    def set_space_after(self, value: float) -> ParagraphStyleRange_32bit: ...
    def set_auto_hyphenate(self, value: bool) -> ParagraphStyleRange_32bit: ...
    def set_hyphenated_word_size(self, value: int) -> ParagraphStyleRange_32bit: ...
    def set_pre_hyphen(self, value: int) -> ParagraphStyleRange_32bit: ...
    def set_post_hyphen(self, value: int) -> ParagraphStyleRange_32bit: ...
    def set_consecutive_hyphens(self, value: int) -> ParagraphStyleRange_32bit: ...
    def set_zone(self, value: float) -> ParagraphStyleRange_32bit: ...
    def set_word_spacing(self, value: List[float]) -> ParagraphStyleRange_32bit: ...
    def set_letter_spacing(self, value: List[float]) -> ParagraphStyleRange_32bit: ...
    def set_glyph_spacing(self, value: List[float]) -> ParagraphStyleRange_32bit: ...
    def set_auto_leading(self, value: float) -> ParagraphStyleRange_32bit: ...
    def set_leading_type(self, value: psapi.enum.LeadingType) -> ParagraphStyleRange_32bit: ...
    def set_hanging(self, value: bool) -> ParagraphStyleRange_32bit: ...
    def set_burasagari(self, value: bool) -> ParagraphStyleRange_32bit: ...
    def set_kinsoku_order(self, value: psapi.enum.KinsokuOrder) -> ParagraphStyleRange_32bit: ...
    def set_every_line_composer(self, value: bool) -> ParagraphStyleRange_32bit: ...
