import sys
# This path structure is generated by the wheel building process
if sys.platform == "linux":
    from ..lib64.photoshopapi.geometry import *
else:
    from ..lib.photoshopapi.geometry import *